{% set name = "cuequivariance-torch" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cuEquivariance/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 761764e4ed6887043d46509d61a4e92a71856d8df38f09843ddbc3c91d9ee703

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./cuequivariance_torch -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - cuequivariance
    - pytorch

test:
  imports:
    - cuequivariance_torch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NVIDIA/cuEquivariance
  summary: CUDA accelerated equivariant operations
  license: Apache-2.0
  license_file: LICENSES/LICENSE

extra:
  recipe-maintainers:
    - fxcoudert
