schema_version: 1

context:
  name: cuequivariance-torch
  version: "0.12.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/NVIDIA/cuEquivariance/archive/refs/tags/v${{ version }}.tar.gz
  sha256: d9bed3013eef97cdf987a392cc7047e87e784f15bc9e87793187f041e0edd886

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install ./cuequivariance_torch -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - cuequivariance
    - pytorch

tests:
  - python:
      imports:
        - cuequivariance_torch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: CUDA accelerated equivariant operations
  license: Apache-2.0
  license_file: LICENSES/LICENSE
  homepage: https://github.com/NVIDIA/cuEquivariance

extra:
  recipe-maintainers:
    - fxcoudert
